# Data parameters
data:
  dataset: imagenette
  data_dir: data/imagenette-data
  input_size: [160, 160]
  input_channels: 3
  num_classes: 10
  valid_size: 0.1

# Training parameters
training:
  output_folder: /content/imagenette_output/
  task: classification
  learner: default
  nb_epochs: 100
  batch_size: 128
  loss:
    name: cross_entropy
  optimizer:
    name: sgd
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0001
  lr_schedule:
  smoother: 0.1
  metrics: ['accuracy', 'auc', 'ap_success', 'ap_errors']
  pin_memory: False
  num_workers: 3
  augmentations:
    normalize: [[0.229, 0.224, 0.225]] # Standard Imagenette normalization

# Model parameters
model:
  name: vgg16
  resume: #vgg16
  hidden_size: 1000
  is_dropout: True
