# Data parameters
data:
    dataset: cityscapes
    data_dir: /data/cityscapes-data/
    input_size: [512, 1024]
    input_channels: 3
    num_classes: 19
    valid_size: 0.1

# Training parameters
training:
    output_folder: /content/output-confidnet-cityscapes
    task: segmentation
    learner: selfconfid
    nb_epochs: 200
    batch_size: 2
    loss:
        name: selfconfid_mse
        weighting: 1
    optimizer:
        name: adam
        lr: 0.0001
        #momentum: 0.9
        #weight_decay: 0.0001
    lr_schedule:
    ft_on_val: False
    metrics: ['accuracy', 'auc', 'ap_success', 'accuracy_success', 'ap_errors', 'accuracy_errors']
    pin_memory: False
    num_workers: 4
    augmentations:
        hflip: True
        #random_crop: [256,512]
        normalize: [[0.286, 0.325, 0.283], [0.176, 0.180, 0.177]]

# Model parameters
model:
    name: segnet_selfconfid
    resume: /content/output-cityscapes/model_epoch_200.ckpt
    is_deconv: True
    is_batchnorm: True
    is_dropout: True
    feature_scale: 4
