# Data parameters
data:
    dataset: fashionmnist
    data_dir: data/fashionmnist-data
    input_size: [28, 28]
    input_channels: 1
    num_classes: 10
    valid_size: 0.1

# Training parameters
training:
    output_folder: /content/output-confidnet-fashionmnist/
    task: classification
    learner: selfconfid
    nb_epochs: 200  # Adjust as needed
    batch_size: 128
    loss:
        name: selfconfid_mse
        weighting: 1
    optimizer:
        name: adam
        lr: 0.0001
    lr_schedule:
    ft_on_val: False
    metrics: ['accuracy', 'auc', 'ap_success', 'ap_errors']
    pin_memory: False
    num_workers: 3
    augmentations:
        normalize: [[0.1307], [0.3081]]  # Standard FashionMNIST normalization

# Model parameters
model:
    name: mlp_selfconfid  # Ensure it's the correct model for FashionMNIST
    hidden_size: 1000
    is_dropout: true
    resume: /content/output-fashionmnist/model_epoch_110.ckpt  # Update with actual checkpoint path
