# Data parameters
data:
  dataset: imagenette
  data_dir: data/imagenette-data
  input_size: [160, 160]
  input_channels: 1
  num_classes: 10
  valid_size: 0.1

# Training parameters
training:
  output_folder: /content/output-confidnet-imagenette/
  task: classification
  learner: selfconfid
  nb_epochs: 200 # Adjust as needed
  batch_size: 128
  loss:
    name: selfconfid_mse
    weighting: 1
  optimizer:
    name: adam
    lr: 0.0001
  lr_schedule:
  ft_on_val: False
  metrics: ['accuracy', 'auc', 'ap_success', 'ap_errors']
  pin_memory: False
  num_workers: 3
  augmentations:
    normalize: [[0.229, 0.224, 0.225]] # Standard FashionMNIST normalization

# Model parameters
model:
  name: vgg16_selfconfid_classic
  resume: /content/imagenette_output/model_epoch_100.ckpt
  hidden_size: 1000
  is_dropout: true
