# Data parameters
data:
  dataset: stl10
  data_dir: data/stl10-data
  input_size: [96, 96]
  input_channels: 3
  num_classes: 10
  valid_size: 0.1

# Training parameters
training:
  output_folder: /content/output-stl10/
  task: classification
  learner: default
  nb_epochs: 250
  batch_size: 128
  loss:
    name: cross_entropy
  optimizer:
    name: sgd
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0005
  lr_schedule:
    #name: multi_step
    #milestones: [50, 120, 200, 250]
  metrics: ['accuracy', 'auc', 'ap_success', 'ap_errors']
  pin_memory: False
  num_workers: 3
  augmentations:
    hflip: True
    rotate: 15
    normalize: [[0.4467, 0.4398, 0.4066], [0.2241, 0.2215, 0.2239]]  # STL-10 mean/std

# Model parameters
model:
  name: vgg16
  resume: vgg16
